### ISSUE TITLE
Syncing with 0.0.7 from older version

### ISSUE THREAD

**Issue by zedr0n** [Team-Hycon/hycon-core#9]
In 0.0.7 the totalWork field was changed

`const totalWork = previousDBBlock.totalWork + (1 / previousDBBlock.nextDifficulty)`

If an older peer tries to initiate sync then it checks whether it should receive or send by using

```
       const remoteHeaderWork = remoteHeaderTip.height - remoteHeaderTip.totalwork
       const localHeaderWork = localHeaderTip.height - localHeaderTip.totalwork

       if (remoteHeaderWork > localHeaderWork) {
                logger.info(`Receiving Headers from ${this.peer.getInfo()}`)
                await this.getHeaders(startHeaderHeight, headersAndBlocks[0])
       } else {
                logger.info(`Sending Headers to ${this.peer.getInfo()}`)
                await this.putHeaders(startHeaderHeight)
       }
```

0.0.7 will return a much larger number than before, so remoteHeaderWork will become negative and a sync will always result in sending headers to 0.0.7 making it impossible to receive blocks. 

respondGetTip should probably check remote version and for <8 give 0 for totalWork?

**Comment by ChosunOne** [comment]
We recommend updating to the latest version.

**Comment by digiuzman** [comment]
This coin Shit coin.. Because team #hycon not give us stable and fast sync node.. #hypocrisy Me and my friends total mining power 1 mhs. we can not mine solo because the team does not release the version that will solve the sync problem.

Only 2 pools have a fully working node version and the team not shared with end-users.
